<?php declare(strict_types=1); ?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Fan Hub Plus — Member</title>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css">
<link rel="stylesheet" href="/admin/assets/css/admin.css">
<link rel="stylesheet" href="/member/assets/css/member.css">
<link rel="stylesheet" href="/member/assets/css/member-fixes.css?v=final">
<link rel="stylesheet" href="/member/assets/css/member-avatar-fixes.css?v=final">
</head>
<body>
<div class="member-shell">
<header class="member-topbar"><a class="member-brand" href="#dashboard"><span class="brand-mark">F+</span><span>Fan Hub Plus</span></a><nav class="member-shortcuts" aria-label="Member sections"><a href="#explore"><i class="fi fi-rr-compass"></i><span>Explore</span></a><a href="#bookmarks"><i class="fi fi-rr-bookmark"></i><span>Bookmarks</span></a><a href="#events"><i class="fi fi-rr-calendar-days"></i><span>Events</span></a><a href="#submissions"><i class="fi fi-rr-document"></i><span>Submissions</span></a><a href="#feedback"><i class="fi fi-rr-comment-alt"></i><span>Feedback</span></a></nav><div class="member-profile"><button id="memberProfileButton" class="member-profile-button"><span id="memberAvatar" class="member-avatar">M</span><span><strong id="memberName">Loading…</strong><small id="memberEmail">Loading profile…</small></span><i class="fi fi-rr-angle-small-down"></i></button><div id="memberProfileMenu" class="member-profile-menu"><a href="#profile"><i class="fi fi-rr-settings"></i>Profile Settings</a><button id="darkModeTop"><i class="fi fi-rr-moon"></i>Dark Mode</button><button id="logoutTop"><i class="fi fi-rr-sign-out-alt"></i>Logout</button></div></div></header>
<aside class="member-rail"><a href="#dashboard" data-section="dashboard" data-tooltip="Dashboard"><i class="fi fi-rr-dashboard"></i></a><a href="#explore" data-section="explore" data-tooltip="Explore"><i class="fi fi-rr-compass"></i></a><a href="#bookmarks" data-section="bookmarks" data-tooltip="Bookmarks"><i class="fi fi-rr-bookmark"></i></a><a href="#events" data-section="events" data-tooltip="Events"><i class="fi fi-rr-calendar-days"></i></a><a href="#submissions" data-section="submissions" data-tooltip="Submissions"><i class="fi fi-rr-document"></i></a><a href="#feedback" data-section="feedback" data-tooltip="Feedback"><i class="fi fi-rr-comment-alt"></i></a><a href="#profile" data-section="profile" data-tooltip="Profile"><i class="fi fi-rr-user"></i></a></aside>
<main class="member-main container">
<section id="dashboardPage" class="member-page" data-page="dashboard"><div class="member-page-head"><div><p class="eyebrow">My dashboard</p><h1 id="greeting">Hello! 👋</h1><p id="followingLine">Your Fan Hub Plus journey at a glance.</p></div><button class="member-primary" data-action="explore"><i class="fi fi-rr-compass"></i>Explore fandoms</button></div><div class="member-grid row g-3"><div class="col-xl-8"><div class="member-card journey-card"><div class="card-heading"><div><p class="eyebrow">Recent activity</p><h2>My Fandom Journey</h2></div><div class="view-toggle"><button class="active" data-activity-view="cards"><i class="fi fi-rr-apps"></i></button><button data-activity-view="list"><i class="fi fi-rr-list"></i></button></div></div><div id="activityPath" class="activity-path"><div class="empty-member"><i class="fi fi-rr-route"></i><h3>No recent activity</h3><p>Your activity will appear here as you explore, bookmark, rate and submit.</p></div></div></div><div class="member-card"><div class="card-heading"><div><p class="eyebrow">Saved for later</p><h2>My Bookmarks</h2></div><a href="#bookmarks" class="text-link">View all <i class="fi fi-rr-arrow-up-right"></i></a></div><div id="bookmarkPreview" class="bookmark-preview"><div class="empty-member"><i class="fi fi-rr-bookmark"></i><h3>No bookmarks yet</h3><p>Save content from Explore to build your personal library.</p></div></div></div></div><aside class="col-xl-4"><div class="member-card stats-card"><div class="card-heading"><div><p class="eyebrow">Your activity</p><h2>Stats</h2></div></div><div class="member-stats"><div><strong id="bookmarkCount">—</strong><span>Bookmarks</span></div><div><strong id="ratingCount">—</strong><span>Ratings given</span></div><div><strong id="submissionCount">—</strong><span>Submissions</span></div><div class="highlight"><strong id="pendingCount">—</strong><span>Pending review</span></div></div></div><div class="member-card events-card"><div class="card-heading"><div><p class="eyebrow">Discover</p><h2>My Events</h2></div><a href="#events" class="text-link"><i class="fi fi-rr-arrow-up-right"></i></a></div><div id="eventPreview" class="event-list"><div class="empty-member"><i class="fi fi-rr-calendar-xmark"></i><h3>No upcoming events</h3><p>Events from the community will appear here.</p></div></div></div></aside></div></section>
<section id="contentPage" class="member-page" data-page="content"><div class="member-page-head"><div><p class="eyebrow" id="contentEyebrow">Member section</p><h1 id="contentTitle">Explore</h1><p id="contentSubtitle">Discover real Fan Hub Plus content.</p></div><div class="member-search"><i class="fi fi-rr-search"></i><input id="exploreSearch" placeholder="Search content, articles, characters…"></div></div><div id="contentList" class="member-content-list"><div class="loading-state">Loading backend records…</div></div></section>
</main>
<nav class="member-quickbar" aria-label="Quick add"><span>Quick add</span><button data-member-action="bookmark" data-tooltip="Bookmark" aria-label="Bookmark"><i class="fi fi-rr-bookmark"></i></button><button data-member-action="rating" data-tooltip="Rate media" aria-label="Rate media"><i class="fi fi-rr-star"></i></button><button data-member-action="submission" data-tooltip="Submit fan article" aria-label="Submit fan article"><i class="fi fi-rr-edit"></i></button><button data-member-action="feedback" data-tooltip="Send feedback" aria-label="Send feedback"><i class="fi fi-rr-comment-alt"></i></button><button id="darkModeQuick" data-tooltip="Dark mode" aria-label="Dark mode"><i class="fi fi-rr-moon"></i></button></nav>
<div id="memberModal" class="member-modal"><div class="member-modal-card"><button id="memberModalClose" class="modal-close"><i class="fi fi-rr-cross"></i></button><p class="eyebrow">Member action</p><h2 id="memberModalTitle">Action</h2><form id="memberActionForm"><div id="memberActionFields" class="member-form-grid"></div><button class="member-primary" type="submit">Save</button></form></div></div>
</div><script src="/member/assets/js/member.js?v=final"></script><script src="/member/assets/js/member-avatar-fixes.js?v=final"></script>
</body></html>
